# Makefile
SHELL=/usr/bin/env /bin/bash

test2:
	gcc -o test `python2.7-config --cflags` test.c `python2.7-config --ldflags`

test3:
	gcc -o test `python3.5-config --cflags` test.c `python3.5-config --ldflags`
